name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install shellcheck

    - name: Lint with shellcheck
      run: |
        find . -name "*.sh" -exec shellcheck {} \;

    - name: Check file permissions
      run: |
        if [ -f "install.sh" ]; then
          if [ ! -x "install.sh" ]; then
            echo "Error: install.sh is not executable"
            exit 1
          fi
        fi

    - name: Validate JSON files
      run: |
        find . -name "*.json" -exec sh -c 'echo "Validating $1"; python -m json.tool "$1" > /dev/null' _ {} \;

    - name: Check for sensitive data
      run: |
        if grep -r "password\|secret\|key" . --exclude-dir=.git --exclude=*.md; then
          echo "Warning: Potential sensitive data found"
        fi

  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run security scan
      uses: github/codeql-action/init@v2
      with:
        languages: javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2